CREATE INDEX IF NOT EXISTS idx_reservas_propiedad_estado ON reservas (propiedad_id, estado);
CREATE INDEX IF NOT EXISTS idx_reservas_huesped_estado ON reservas (huesped_id, estado);
CREATE INDEX IF NOT EXISTS idx_reservas_fecha_entrada ON reservas (fecha_entrada);
CREATE INDEX IF NOT EXISTS idx_pagos_reserva_estado ON pagos (reserva_id, estado);
CREATE INDEX IF NOT EXISTS idx_pagos_estado ON pagos (estado);
CREATE INDEX IF NOT EXISTS idx_propiedades_estado ON propiedades (estado);
CREATE INDEX IF NOT EXISTS idx_propiedades_ciudad ON propiedades (ciudad);
CREATE INDEX IF NOT EXISTS idx_propiedades_precio ON propiedades (precio_por_noche);
CREATE INDEX IF NOT EXISTS idx_propiedades_tipo ON propiedades (tipo_propiedad);
CREATE INDEX IF NOT EXISTS idx_propiedades_propietario ON propiedades (propietario_id);
CREATE INDEX IF NOT EXISTS idx_imagenes_propiedad ON imagenes_propiedad (propiedad_id, orden);
CREATE INDEX IF NOT EXISTS idx_propiedad_amenidades_propiedad ON propiedad_amenidades (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_resenas_propiedad ON resenas (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_resenas_anfitrion ON resenas (anfitrion_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transacciones_wallet ON wallet_transacciones (wallet_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastos_propiedad ON gastos_mantenimiento (propiedad_id, fecha DESC);
CREATE INDEX IF NOT EXISTS idx_fechas_bloqueadas_propiedad ON fechas_bloqueadas (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_precios_especiales_propiedad ON precios_especiales (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (rol);
CREATE INDEX IF NOT EXISTS idx_store_productos_activo ON store_productos (activo, orden);
CREATE INDEX IF NOT EXISTS idx_store_servicios_activo ON store_servicios (activo, orden);
CREATE INDEX IF NOT EXISTS idx_reserva_store_items_reserva ON reserva_store_items (reserva_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_fecha ON audit_log (fecha_accion DESC);
