apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: admin@boogierent.com
        disableResolveMessage: false
