apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram-alerts

contactPoints:
  - orgId: 1
    name: telegram-alerts
    receivers:
      - uid: telegram-alerts
        type: telegram
        settings:
          bottoken: "8626940353:AAFpMY7-7ikTtOHXg2psilXQ6MFixrs_3oA"
          chatid: "6085825911"
        disableResolveMessage: false
